import type { Currency } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', countryCode: 'ae' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', countryCode: 'af' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', countryCode: 'al' },
  { code: 'AMD', name: 'Armenian Dram', symbol: 'դր.', countryCode: 'am' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', countryCode: 'cw' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', countryCode: 'ao' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', countryCode: 'ar' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', countryCode: 'au' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', countryCode: 'aw' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', countryCode: 'az' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', countryCode: 'ba' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', countryCode: 'bb' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', countryCode: 'bd' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', countryCode: 'bg' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', countryCode: 'bh' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', countryCode: 'bi' },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: '$', countryCode: 'bm' },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', countryCode: 'bn' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', countryCode: 'bo' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', countryCode: 'br' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', countryCode: 'bs' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', countryCode: 'bt' },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', countryCode: 'bw' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', countryCode: 'by' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', countryCode: 'bz' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', countryCode: 'ca' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', countryCode: 'cd' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', countryCode: 'ch' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', countryCode: 'cl' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', countryCode: 'cn' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', countryCode: 'co' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', countryCode: 'cr' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', countryCode: 'cu' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', countryCode: 'cv' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', countryCode: 'cz' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', countryCode: 'dj' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', countryCode: 'dk' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', countryCode: 'do' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', countryCode: 'dz' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', countryCode: 'eg' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', countryCode: 'er' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', countryCode: 'et' },
  { code: 'EUR', name: 'Euro', symbol: '€', countryCode: 'eu' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', countryCode: 'fj' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', countryCode: 'fk' },
  { code: 'GBP', name: 'British Pound', symbol: '£', countryCode: 'gb' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', countryCode: 'ge' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', countryCode: 'gh' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', countryCode: 'gi' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', countryCode: 'gm' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', countryCode: 'gn' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', countryCode: 'gt' },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$', countryCode: 'gy' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', countryCode: 'hk' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', countryCode: 'hn' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', countryCode: 'hr' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', countryCode: 'ht' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', countryCode: 'hu' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', countryCode: 'id' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', countryCode: 'il' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', countryCode: 'in' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', countryCode: 'iq' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', countryCode: 'ir' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', countryCode: 'is' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', countryCode: 'jm' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', countryCode: 'jo' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', countryCode: 'jp' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', countryCode: 'ke' },
  { code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', countryCode: 'kg' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', countryCode: 'kh' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', countryCode: 'km' },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩', countryCode: 'kp' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', countryCode: 'kr' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', countryCode: 'kw' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', countryCode: 'ky' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', countryCode: 'kz' },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', countryCode: 'la' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', countryCode: 'lb' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', countryCode: 'lk' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', countryCode: 'lr' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', countryCode: 'ls' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', countryCode: 'ly' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', countryCode: 'ma' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', countryCode: 'md' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', countryCode: 'mg' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', countryCode: 'mk' },
  { code: 'MMK', name: 'Myanma Kyat', symbol: 'K', countryCode: 'mm' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', countryCode: 'mn' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', countryCode: 'mo' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', countryCode: 'mr' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', countryCode: 'mu' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: '.ރ', countryCode: 'mv' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', countryCode: 'mw' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', countryCode: 'mx' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', countryCode: 'my' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', countryCode: 'mz' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', countryCode: 'na' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', countryCode: 'ng' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', countryCode: 'ni' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', countryCode: 'no' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', countryCode: 'np' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', countryCode: 'nz' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', countryCode: 'om' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', countryCode: 'pa' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.', countryCode: 'pe' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', countryCode: 'pg' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', countryCode: 'ph' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', countryCode: 'pk' },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', countryCode: 'pl' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', countryCode: 'py' },
  { code: 'QAR', name: 'Qatari Rial', symbol: '﷼', countryCode: 'qa' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', countryCode: 'ro' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', countryCode: 'rs' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', countryCode: 'ru' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', countryCode: 'rw' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', countryCode: 'sa' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', countryCode: 'sb' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', countryCode: 'sc' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', countryCode: 'sd' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', countryCode: 'se' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', countryCode: 'sg' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', countryCode: 'sh' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', countryCode: 'sl' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', countryCode: 'so' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', countryCode: 'sr' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', countryCode: 'ss' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db', countryCode: 'st' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', countryCode: 'sy' },
  { code: 'SZL', name: 'Eswatini Lilangeni', symbol: 'L', countryCode: 'sz' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', countryCode: 'th' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', countryCode: 'tj' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', countryCode: 'tm' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', countryCode: 'tn' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', countryCode: 'to' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', countryCode: 'tr' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TT$', countryCode: 'tt' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', countryCode: 'tw' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', countryCode: 'tz' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', countryCode: 'ua' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', countryCode: 'ug' },
  { code: 'USD', name: 'US Dollar', symbol: '$', countryCode: 'us' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', countryCode: 'uy' },
  { code: 'UZS', name: 'Uzbekistan Som', symbol: 'soʻm', countryCode: 'uz' },
  { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S.', countryCode: 've' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', countryCode: 'vn' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', countryCode: 'vu' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'T', countryCode: 'ws' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', countryCode: 'cm' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', countryCode: 'ag' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', countryCode: 'sn' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', countryCode: 'pf' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', countryCode: 'ye' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', countryCode: 'za' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', countryCode: 'zm' },
];
